/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => OpenInVSCodePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_child_process = require("child_process");
var DEFAULT_OPENERS = [
  {
    id: "vscode",
    name: "Open in VSCode",
    command: "code",
    // `-g` is dropped for folders / unopened files, leaving a plain `code {path}`.
    args: "-g\n{path}:{line}:{col}"
  }
];
function uid() {
  return Math.random().toString(36).slice(2, 10);
}
var OpenInVSCodePlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { openers: DEFAULT_OPENERS };
  }
  async onload() {
    await this.loadSettings();
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (!(file instanceof import_obsidian.TFile) && !(file instanceof import_obsidian.TFolder))
          return;
        for (const opener of this.settings.openers) {
          menu.addItem((item) => {
            item.setTitle(opener.name || "Open").setIcon("code").onClick(() => this.openWith(opener, file));
          });
        }
      })
    );
    for (const opener of this.settings.openers) {
      this.addCommand({
        id: `open-current-${opener.id}`,
        name: `Open current file in ${opener.name || "external editor"}`,
        callback: () => {
          const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
          if (!view || !view.file) {
            new import_obsidian.Notice("No active file to open.");
            return;
          }
          this.openWith(opener, view.file);
        }
      });
    }
    this.addSettingTab(new OpenInVSCodeSettingTab(this.app, this));
  }
  onunload() {
  }
  getOpenLeafForFile(file) {
    for (const leaf of this.app.workspace.getLeavesOfType("markdown")) {
      const view = leaf.view;
      if (view?.file?.path === file.path)
        return leaf;
    }
    return null;
  }
  getAbsolutePath(file) {
    const adapter = this.app.vault.adapter;
    return `${adapter.getBasePath()}/${file.path}`.replace(/\\/g, "/");
  }
  /**
   * Turn an opener template into a concrete argument list.
   * - Substitutes {path}/{line}/{col}.
   * - Drops any token containing {line}/{col} when line/col is unavailable.
   * - Drops a flag token (starts with `-`) directly above a dropped token.
   * - Ensures the path is always present (appends it if no token kept it).
   */
  buildArgs(opener, absPath, line, col) {
    const tokens = opener.args.split("\n").map((t) => t.trim()).filter((t) => t.length > 0);
    const lineStr = line != null ? String(line) : "";
    const colStr = col != null ? String(col) : "";
    const substituted = tokens.map(
      (t) => t.replace(/\{path\}/g, absPath).replace(/\{line\}/g, lineStr).replace(/\{col\}/g, colStr)
    );
    const dropped = tokens.map((orig, i) => {
      const needsLineCol = /\{line\}|\{col\}/.test(orig);
      if (needsLineCol && (line == null || col == null))
        return true;
      if (substituted[i].length === 0)
        return true;
      return false;
    });
    for (let i = 0; i < tokens.length; i++) {
      if (!dropped[i] && /^-/.test(tokens[i]) && i + 1 < tokens.length && dropped[i + 1]) {
        dropped[i] = true;
      }
    }
    const result = substituted.filter((_, i) => !dropped[i]);
    if (!result.some((t) => t.includes(absPath))) {
      result.push(absPath);
    }
    return result;
  }
  openWith(opener, file) {
    const absPath = this.getAbsolutePath(file);
    let line = null;
    let col = null;
    if (file instanceof import_obsidian.TFile) {
      const leaf = this.getOpenLeafForFile(file);
      if (leaf) {
        const view = leaf.view;
        const cursor = view.editor.getCursor();
        line = cursor.line + 1;
        col = cursor.ch + 1;
      }
    }
    const args = this.buildArgs(opener, absPath, line, col);
    const command = (opener.command || "code").trim();
    const full = [command, ...args.map(quoteIfNeeded)].join(" ");
    try {
      const child = (0, import_child_process.spawn)(full, { shell: true, stdio: "ignore" });
      child.on("error", (err) => {
        new import_obsidian.Notice(
          `Failed to run "${command}". Check the command in settings. (${err.message})`
        );
      });
    } catch (err) {
      new import_obsidian.Notice(`Failed to launch: ${err.message}`);
    }
  }
  async loadSettings() {
    const data = await this.loadData();
    if (data && Array.isArray(data.openers) && data.openers.length > 0) {
      this.settings = { openers: data.openers };
    } else {
      this.settings = { openers: DEFAULT_OPENERS };
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
function quoteIfNeeded(token) {
  return /\s/.test(token) && !/^".*"$/.test(token) ? `"${token}"` : token;
}
var OpenInVSCodeSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("p", {
      text: "Configure one or more external editors. Each adds an \u201COpen in \u2026\u201D entry to the file context menu. Placeholders: {path}, {line}, {col}. Put a flag like -g on the line above a {line}/{col} token so it is dropped automatically for folders.",
      cls: "setting-item-description"
    });
    this.plugin.settings.openers.forEach((opener, index) => {
      const block = containerEl.createDiv({ cls: "oic-opener" });
      block.style.border = "1px solid var(--background-modifier-border)";
      block.style.borderRadius = "6px";
      block.style.padding = "10px";
      block.style.marginBottom = "12px";
      new import_obsidian.Setting(block).setName("Menu label").addText(
        (t) => t.setValue(opener.name).setPlaceholder("Open in VSCode").onChange(async (v) => {
          this.plugin.settings.openers[index].name = v;
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian.Setting(block).setName("Command").setDesc("Executable name or absolute path, e.g. code or C:\\...\\code.cmd").addText(
        (t) => t.setValue(opener.command).setPlaceholder("code").onChange(async (v) => {
          this.plugin.settings.openers[index].command = v;
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian.Setting(block).setName("Arguments (one per line)").setDesc("Use {path}, {line}, {col}. Example for VSCode:  -g  then  {path}:{line}:{col}").addTextArea((t) => {
        t.setValue(opener.args).onChange(async (v) => {
          this.plugin.settings.openers[index].args = v;
          await this.plugin.saveSettings();
        });
        t.inputEl.rows = 3;
        t.inputEl.style.width = "100%";
      });
      new import_obsidian.Setting(block).setName("").addButton(
        (b) => b.setButtonText("Delete").setWarning().onClick(async () => {
          this.plugin.settings.openers.splice(index, 1);
          await this.plugin.saveSettings();
          this.display();
        })
      );
    });
    new import_obsidian.Setting(containerEl).setName("Add opener").addButton(
      (b) => b.setButtonText("+ Add").onClick(async () => {
        this.plugin.settings.openers.push({
          id: uid(),
          name: "Open in \u2026",
          command: "code",
          args: "{path}"
        });
        await this.plugin.saveSettings();
        this.display();
      })
    ).addButton(
      (b) => b.setButtonText("Restore VSCode default").onClick(async () => {
        this.plugin.settings.openers = DEFAULT_OPENERS.map((o) => ({ ...o }));
        await this.plugin.saveSettings();
        this.display();
      })
    );
  }
};
